global:
  imageRegistry: docker.io
  imagePullSecrets: []

#opensearch-master:
#  image:
#    repository: "opensearchproject/opensearch"
#    # override image tag, which is .Chart.AppVersion by default
#    # change tag to an old version like "2.6.0" if OpenSearch pod failed to start on your node with old CPU with error log message "Fatal glibc error: CPU does not support x86-64-v2"
#    tag: "2.11.1"
#    pullPolicy: "IfNotPresent"
#  opensearchJavaOpts: "-Xmx512M -Xms512M"
#  replicas: 1
#  resources:
#    requests:
#      cpu: "100m"
#      memory: "512Mi"
opensearch-data:
#  image:
#    repository: "opensearchproject/opensearch"
#    # override image tag, which is .Chart.AppVersion by default
#    # change tag to an old version like "2.6.0" if OpenSearch pod failed to start on your node with old CPU with error log message "Fatal glibc error: CPU does not support x86-64-v2"
#    tag: "2.11.1"
#    pullPolicy: "IfNotPresent"
  service:
    type: NodePort
    nodePort: 30920
#  opensearchJavaOpts: "-Xmx1536M -Xms1536M"
#  replicas: 3
#  resources:
#    requests:
#      cpu: "200m"
#      memory: "1536Mi"

opensearch-dashboards:
  enabled: false
opensearch-curator:
  enabled: true
#  configMaps:
#  # Delete indices older than 7 days
#    action_file_yml: |-
#      ---
#      actions:
#        1:
#          action: delete_indices
#          description: "Clean up opensearch by deleting old logging indices"
#          options:
#            timeout_override:
#            continue_if_exception: False
#            disable_action: False
#            ignore_empty_list: True
#          filters:
#          - filtertype: pattern
#            kind: regex
#            value: ^.+-logs
#            exclude: False
#          - filtertype: age
#            source: name
#            direction: older
#            timestring: '%Y.%m.%d'
#            unit: days
#            unit_count: 7
#            field:
#            stats_result:
#            epoch:
#            exclude: False
#        2:
#          action: delete_indices
#          description: "Clean up opensearch by deleting old events indices"
#          options:
#            timeout_override:
#            continue_if_exception: False
#            disable_action: False
#            ignore_empty_list: True
#          filters:
#          - filtertype: pattern
#            kind: regex
#            value: ^.+-events
#            exclude: False
#          - filtertype: age
#            source: name
#            direction: older
#            timestring: '%Y.%m.%d'
#            unit: days
#            unit_count: 7
#            field:
#            stats_result:
#            epoch:
#            exclude: False
#        3:
#          action: delete_indices
#          description: "Clean up opensearch by deleting old auditing indices"
#          options:
#            timeout_override:
#            continue_if_exception: False
#            disable_action: False
#            ignore_empty_list: True
#          filters:
#          - filtertype: pattern
#            kind: regex
#            value: ^.+-auditing
#            exclude: False
#          - filtertype: age
#            source: name
#            direction: older
#            timestring: '%Y.%m.%d'
#            unit: days
#            unit_count: 7
#            field:
#            stats_result:
#            epoch:
#            exclude: False
#        4:
#          action: delete_indices
#          description: "Clean up opensearch by deleting old notification history indices"
#          options:
#            timeout_override:
#            continue_if_exception: False
#            disable_action: False
#            ignore_empty_list: True
#          filters:
#          - filtertype: pattern
#            kind: regex
#            value: ^.+-notification-history
#            exclude: False
#          - filtertype: age
#            source: name
#            direction: older
#            timestring: '%Y.%m.%d'
#            unit: days
#            unit_count: 7
#            field:
#            stats_result:
#            epoch:
#            exclude: False
#        5:
#          action: delete_indices
#          description: "Clean up opensearch by deleting old istio indices"
#          options:
#            timeout_override:
#            continue_if_exception: False
#            disable_action: False
#            ignore_empty_list: True
#          filters:
#          - filtertype: pattern
#            kind: prefix
#            value: whizard
#            exclude: False
#          - filtertype: age
#            source: name
#            direction: older
#            timestring: '%Y.%m.%d'
#            unit: days
#            unit_count: 7
#            field:
#            stats_result:
#            epoch:
#            exclude: False
#    # Having config_yaml WILL override the other config
#    config_yml: |-
#      ---
#      client:
#        hosts:
#          - opensearch-cluster-data.kubesphere-logging-system.svc
#        port: 9200
#        # url_prefix:
#        use_ssl: True
#        # certificate:
#        # client_cert:
#        # client_key:
#        ssl_no_validate: True
#        http_auth: admin:admin