kind: ClusterRole
rules:
  - apiGroups:
      - 'extensions.kubesphere.io'
      - 'iam.kubesphere.io'
      - 'devops.kubesphere.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
      - 'rbac.authorization.k8s.io'
      - 'monitoring.coreos.com'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'apiextensions.k8s.io'
    resources:
      - 'customresourcedefinitions'
    verbs:
      - '*'
  - apiGroups:
      - 'alerting.kubesphere.io'
    resources:
      - 'clusterrulegroups'
    verbs:
      - '*'

---
kind: Role
rules:
  - apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'networking.k8s.io'
    resources:
      - 'ingresses'
      - 'networkpolicies'
    verbs:
      - '*'
