global:
  imageRegistry:
  imagePullSecrets: []
  
extension:
  apiserver:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        memory: 128Mi
        cpu: 100m

agent:
  apiserver:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        memory: 128Mi
        cpu: 100m
  controller:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
  jenkins:
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 6Gi
        limits:
          cpu: 2
          memory: 6Gi # recommend set same as requests.memory
      # smtp server settings for notification
      smtp:
        EMAIL_SMTP_HOST: "mail.example.com"
        EMAIL_SMTP_PORT: "465"
        EMAIL_USE_SSL: false
        EMAIL_FROM_NAME: "KubeSphere"
        EMAIL_FROM_ADDR: "admin@example.com"
        EMAIL_FROM_PASS: "P@ssw0rd"
      # sonarQube settings
      sonarqube:
        serverUrl: ""
        authToken: ""
    persistence:
      size: 16Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    kubeconfigEnabled: true

    unclassified:
      gitLabServers:
        - name: "https://gitlab.com"
          serverUrl: "https://gitlab.com"
