extension:
  apiserver:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        memory: 128Mi
        cpu: 100m

agent:
  apiserver:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        memory: 128Mi
        cpu: 100m
  controller:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
  jenkins:
    securityRealm:
      openIdConnect:
        # The kubesphere-core api used for jenkins OIDC
        # If you want to access to jenkinsWebUI, the kubesphereCoreApi must be specified and browser-accessible
        # Modifying this configuration will take effect only during installation
        # If you wish for changes to take effect after installation, you need to update the jenkins-casc-config ConfigMap, copy the securityRealm configuration from jenkins.yaml to jenkins_user.yaml, save, and wait for approximately 70 seconds for the changes to take effect.
        kubesphereCoreApi: "http://ks-apiserver:30880"
        # The jenkins web URL used for OIDC redirect
        jenkinsURL: "http://devops-jenkins:30180"
    Master:
      resources:
        requests:
          cpu: 0.5
          memory: 6Gi
        limits:
          cpu: 2
          memory: 6Gi # recommend set same as requests.memory
      # smtp server settings for notification
      smtp:
        EMAIL_SMTP_HOST: "mail.example.com"
        EMAIL_SMTP_PORT: "465"
        EMAIL_USE_SSL: false
        EMAIL_FROM_NAME: "KubeSphere"
        EMAIL_FROM_ADDR: "admin@example.com"
        EMAIL_FROM_PASS: "P@ssw0rd"
      # sonarQube settings
      sonarqube:
        serverUrl: ""
        authToken: ""
    persistence:
      size: 16Gi
      storageClass: ""
      accessMode: ReadWriteOnce
    kubeconfigEnabled: true

