{{- if lookup "v1" "PersistentVolumeClaim" .Release.Namespace "deepseek-models" | len | eq 0 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: deepseek-models
spec:
  accessModes:
    {{ .Values.persistence.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}