kind: ConfigMap
apiVersion: v1
metadata:
  name: {{  include "kube-events-exporter.fullname" . }}
  namespace: {{  include "kube-events-exporter.namespaceOverride" . }}
data:
  events-exporter.yaml: |
    sinks:
      stdout: {}
