{{- if .Values.certs.secret.create }}

{{- $jaegerOperatorFullname := include "jaeger-operator.fullname" . }}
{{- $ca := genCA $jaegerOperatorFullname 3650 }}
{{- $cn := printf "%s-admission-webhook" $jaegerOperatorFullname }}
{{- $altName1 := printf "%s.%s" $jaegerOperatorFullname .Release.Namespace }}
{{- $altName2 := printf "$s.%s.svc" $jaegerOperatorFullname .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: v1
data:
  ca.crt: {{ b64enc $ca.Cert | quote }}
  tls.crt: {{ b64enc  $cert.Cert | quote }}
  tls.key: {{ b64enc  $cert.Key | quote }}
kind: Secret
metadata:
  name: "jaeger-operator-service-cert"
type: Opaque

{{- end }}
