apiVersion: v2
name: extension
description: A Helm chart for KubeSphere-Extension DevOps extension
type: application
version: 1.1.3
appVersion: v4.1.3
home: https://kubesphere.io/devops/
sources:
  - https://github.com/kubesphere/ks-devops
  - https://github.com/kubesphere-sigs/ks-devops-helm-chart
annotations:
  extensions.kubesphere.io/devops: extension
