{{- if .Values.exactSecurityRealm.oic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-oauthclient
  namespace: kubesphere-system
  labels:
    config.kubesphere.io/type: oauthclient
type: config.kubesphere.io/oauthclient
stringData:
  configuration.yaml: |
    name: {{ .Values.exactSecurityRealm.oic.clientId }}
    secret: {{ .Values.exactSecurityRealm.oic.clientSecret }}
    grantMethod: auto
    trusted: true
    accessTokenInactivityTimeoutSeconds: 3600
    {{- with .Values.redirectURIs }}
    redirectURIs:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- $scopes := .Values.exactSecurityRealm.oic.scopes }}
    {{- $scopeList := split " " $scopes }}
    scopeRestrictions:
    {{- range $index, $item := $scopeList }}
      - {{ $item }}
    {{- end }}
    {{- end }}
