apiVersion: v1
name: frontend
description: Frontend of network extension.
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere-extensions
