apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  index.js: {{ .Values.indexJsContent | quote}}
