{{- if or (.Values.defaultIssuer.selfSigned.enabled) (.Values.defaultIssuer.CA.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: check-default-issuer-job
  namespace: {{ include "cert-manager.namespace" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: {{ default (default "docker.io" (.Values.global).imageRegistry) .Values.defaultIssuer.deleteJob.image.registry }}/{{ .Values.defaultIssuer.deleteJob.image.repository }}:{{ .Values.defaultIssuer.deleteJob.image.tag }}
          command:
            - /bin/sh
            - '-c'
            - 'cd /cert-manager && ./default-issuer-check.sh default-issuer'
          volumeMounts:
            - mountPath: /cert-manager
              name: check-status
      volumes:
        - name: check-status
          configMap:
            name: {{ .Release.Name }}-check-status
            defaultMode: 0777
      serviceAccountName: {{ .Release.Name }}-sa
      restartPolicy: Never
{{- end }}