{{- if or (.Values.defaultIssuer.selfSigned.enabled) (.Values.defaultIssuer.CA.enabled) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-issuer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
{{- include "cert-manager.issuer" . | indent 2 }}
{{- end }}