global:
  imageRegistry: docker.io
  imagePullSecrets: [ ]

apps:
  enabled: true
  image:
    repository: kubesphere/apps-manage
    pullPolicy: IfNotPresent
    tag: "v2.0.2"
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

