apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubefed-controller
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: kubefed-admission-webhook
