apiVersion: v2
name: backend
description: Backend of kubefed extension.
type: application
version: 0.1.0
appVersion: "v1.0.0"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere-extensions/kubefed
