# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kubesphere/kubefed-extension
  pullPolicy: Always
  pullSecrets: []
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

nodeSelector: {}

tolerations: []

affinity: {}

kubectl:
  image:
    repository: kubesphere/kubectl
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: v1.27.4
