apiVersion: v1
name: frontend
description: Frontend of whizard-notification extension.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere-extensions
