apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRole
metadata:
  name: devops-authenticated
rules:
  - apiGroups:
      - devops.kubesphere.io
    resources:
      - ci
      - namespaces
      - clustersteptemplates
      - clustertemplates
      - scms/servers
      - scms/organizations
      - scms/organizations/repositories
    verbs:
      - get
      - list
  - apiGroups:
      - devops.kubesphere.io
    resources:
      - clustertemplates/render
      - clustersteptemplates/render
      - scms/servers
      - scms/verify
      - jenkins/serverList
      - jenkins/projectList
    verbs:
      - create
  - apiGroups:
      - gitops.kubesphere.io
    resources:
      - clusters
    verbs:
      - list
  - nonResourceURLs:
      - search
      - crumbissuer
      - webhook/git
      - webhook/github
      - webhook/generic-trigger
      - webhooks/jenkins
      - webhooks/scm
      - jenkins
      - jenkins/*
      - oauth/authenticate
    verbs:
      - get
      - create

---
apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRoleBinding
metadata:
  name: devops-authenticated
roleRef:
  apiGroup: iam.kubesphere.io
  kind: GlobalRole
  name: devops-authenticated
subjects:
  - apiGroup: iam.kubesphere.io
    kind: Group
    name: system:authenticated
---
apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRole
metadata:
  name: devops-anonymous
rules:
- apiGroups:
  - devops.kubesphere.io
  resources:
  - webhook
  - webhooks
  verbs:
  - get
  - create
---
apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRoleBinding
metadata:
  name: devops-anonymous
roleRef:
  apiGroup: iam.kubesphere.io
  kind: GlobalRole
  name: devops-anonymous
subjects:
- apiGroup: iam.kubesphere.io
  kind: Group
  name: system:unauthenticated
