{{- if .Values.jenkins.Master.UseSecurity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jenkins.fullnameOverride }}
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
  labels:
    {{- include "extension.labels" . | nindent 4 }}
    heritage: "{{ .Release.Service }}"
    devops.kubesphere.io/component: Jenkins
type: Opaque
data:
  jenkins-admin-user: {{ .Values.jenkins.Master.AdminUser | b64enc | quote }}
  jenkins-admin-password: {{ template "jenkins.password" . }}
  jenkins-admin-token: {{ template "jenkins.adminToken" . }}
{{- end }}