apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opensearch-curator.fullname" . }}-config
  labels:
    app: {{ template "opensearch-curator.name" . }}
    chart: {{ template "opensearch-curator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ template "opensearch-curator.namespace" . }}
data:
  action_file.yml: {{ required "A valid .Values.configMaps.action_file_yml entry is required!" (toYaml .Values.configMaps.action_file_yml | indent 2) }}
  config.yml: {{ required "A valid .Values.configMaps.config_yml entry is required!" (toYaml .Values.configMaps.config_yml | indent 2) }}
