apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicemesh-apiserver
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: servicemesh-apiserver
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: servicemesh-apiserver
      tier: backend
  template:
    metadata:
      labels:
        app: servicemesh-apiserver
        tier: backend
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      containers:
        - command:
            - apiserver
            - --logtostderr=true
          image: "{{ template "apiserver.image" . }}"
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          name: servicemesh-apiserver
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/servicemesh/
              name: servicemesh-config
            - mountPath: /etc/localtime
              name: host-time
              readOnly: true
          {{- if .Values.apiserver.extraVolumeMounts }}
          {{- toYaml .Values.apiserver.extraVolumeMounts | nindent 8 }}
          {{- end }}
          env:
          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 8 }}
          {{- end }}
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 15
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: servicemesh-config
          name: servicemesh-config
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
      {{- if .Values.apiserver.extraVolumes }}
      {{ toYaml .Values.apiserver.extraVolumes | nindent 6 }}
      {{- end }}