apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-istio-config"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
data:
data:
  istio-config.yaml: |
    {{- include "istio-config" . | nindent 4 }}
