apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-viewer-sa
  namespace: istio-system
  
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: kiali-viewer-secret
  namespace: istio-system
  annotations:
    kubernetes.io/service-account.name: "kiali-viewer-sa"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-viewer-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-viewer-rolebinding
subjects:
  - kind: ServiceAccount
    name: kiali-viewer-sa
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: kiali-viewer-role
  apiGroup: rbac.authorization.k8s.io
