apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicemesh-apiserver
    tier: backend
    version: {{ .Chart.AppVersion }}
  name: servicemesh-apiserver
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: servicemesh-apiserver
    tier: backend
  type: ClusterIP
