{{- if .Values.configs.styles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-custom-styles
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.repoServer.name "name" .Values.repoServer.name) | nindent 4 }}
data:
  custom.styles.css: |
    {{- .Values.configs.styles | nindent 4 }}
{{- end }}