{{- if and .Values.externalRedis.password (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "argo-cd.redis.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    {{- include "argo-cd.labels" (dict "context" $) | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | b64enc }}
{{- end }}
