{{- if .Values.apiserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}-apiserver
  labels:
    app: gateway-apiserver
    tier: backend
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.replicaCount }}
  selector:
    matchLabels:
      app: gateway-apiserver
      tier: backend
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: gateway-apiserver
        tier: backend
        {{- include "gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      {{- with .Values.apiserver.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - apiserver
            - --logtostderr=true
          {{- with .Values.apiserver.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ template "apiserver.image" . }}"
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiserver.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/gateway/
              name: gateway-config
            - mountPath: /etc/localtime
              name: host-time
              readOnly: true
          {{- if .Values.apiserver.extraVolumeMounts }}
          {{- toYaml .Values.apiserver.extraVolumeMounts | nindent 10 }}
          {{- end }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: gateway-config
          configMap:
            name: {{ include "gateway.fullname" . }}-config
            defaultMode: 420
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ""
      {{- if .Values.apiserver.extraVolumes }}
      {{ toYaml .Values.apiserver.extraVolumes | nindent 6 }}
      {{- end }}
  {{- end }}