apiVersion: extensions.kubesphere.io/v1alpha1
kind: APIService
metadata:
  name: v2alpha1.gateway.kubesphere.io
spec:
  group: gateway.kubesphere.io
  version: v2alpha1
  url: http://{{ include "gateway.fullname" . }}-apiserver.{{ .Release.Namespace }}.svc:{{ .Values.apiserver.service.port }}
#  insecureSkipTLSVerify: true
status:
  state: Available
