{{- if .Values.upgradeGateway.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gateway.fullname" . }}-cluster-gateway-upgrader
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: upgrade-cluster-gateway
          image: {{ include "common.images.image" (dict "imageRoot" .Values.upgradeGateway.image "global" .Values.global) }}
          command: ["/bin/bash"]
          args:
            - '-c'
            - 'cd /upgrade && ./upgrade-cluster-gateway.sh /etc/gateway'
          volumeMounts:
            - name: upgrade
              mountPath: /upgrade
            - name: gateway-config
              mountPath: /etc/gateway
      volumes:
        - name: upgrade
          configMap:
            name: {{ include "gateway.fullname" . }}-upgrader-config
            defaultMode: 0777
        - name: gateway-config
          emptyDir: {}
      restartPolicy: Never
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
  backoffLimit: 4
{{- end }}