{{- if .Values.upgradeGateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-upgrader-config
  labels:
      {{- include "gateway.labels" . | nindent 4 }}
data:
  override.yaml: | {{ .Values.upgradeGateway.gatewayOverride | toYaml | nindent 4 }}
  upgrade-cluster-gateway.sh: | {{ .Files.Get "files/upgrade-cluster-gateway.sh" | nindent 4 }}
{{- end }}
