{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    gateway:
      namespace: {{ .Values.config.gateway.namespace | quote }}
      valuesOverride: {{- include "gateway.valueOverride" . | indent 8 }}
      exposeNodeSelector: {{ .Values.config.gateway.exposeNodeSelector | quote }}
      versionConstraint: {{ .Values.config.gateway.versionConstraint | quote }}
      logSearchEndpoint: {{ .Values.config.gateway.logSearchEndpoint | quote }}
  {{- end }}