apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRole
metadata:
  name: ks-gateway-authenticated
rules:
  - apiGroups:
      - gateway.kubesphere.io
    resources:
      - appversions
      - appversions/values
    verbs:
      - get
      - list

---
apiVersion: iam.kubesphere.io/v1beta1
kind: GlobalRoleBinding
metadata:
  name: ks-gateway-authenticated
roleRef:
  apiGroup: iam.kubesphere.io
  kind: GlobalRole
  name: ks-gateway-authenticated
subjects:
  - apiGroup: iam.kubesphere.io
    kind: Group
    name: system:authenticated
