apiVersion: iam.kubesphere.io/v1beta1
kind: Category
metadata:
  name: ks-gateway-namespace
  labels:
    iam.kubesphere.io/scope: namespace
    kubesphere.io/managed: "true"
spec:
  description:
    en: Gateway
    zh: 网关
  displayName:
    en: Gateway
    zh: 网关
---
apiVersion: iam.kubesphere.io/v1beta1
kind: Category
metadata:
  name: ks-gateway-workspace
  labels:
    iam.kubesphere.io/scope: workspace
    kubesphere.io/managed: "true"
spec:
  description:
    en: Gateway
    zh: 网关
  displayName:
    en: Gateway
    zh: 网关