{{ if (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule") }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: prometheus-ingress-rules
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: ingress.rules
      rules:
        - expr: >
            nginx_ingress_controller_requests{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_requests'
        - expr: >
            nginx_ingress_controller_request_duration_seconds_sum{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_request_duration_seconds_sum'
        - expr: >
            nginx_ingress_controller_request_duration_seconds_count{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_request_duration_seconds_count'
        - expr: >
            nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_request_duration_seconds_bucket'
        - expr: >
            nginx_ingress_controller_response_size_sum{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_response_size_sum'
        - expr: >
            nginx_ingress_controller_request_size_sum{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_request_size_sum'
        - expr: >
            nginx_ingress_controller_nginx_process_resident_memory_bytes{exported_namespace!=""} * on (cluster, exported_namespace) group_left(workspace)(label_replace(kube_namespace_labels{job = "kube-state-metrics"}, "exported_namespace","$1","namespace","(.*)"))
          record: 'nginx_ingress_controller_kubesphere_nginx_process_resident_memory_bytes'
{{ end -}}