apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-extension" .Release.Name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-extension" .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-extension" .Release.Name }}
    namespace: {{ .Release.Namespace }}
