apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.kubeEdgeProxy.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  name: kubeedge-proxy-sa
  namespace: {{ template "cloudcore.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeedge-proxy
  {{- with .Values.kubeEdgeProxy.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeedge-proxy
subjects:
- kind: ServiceAccount
  name: kubeedge-proxy-sa
  namespace: {{ template "cloudcore.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeedge-proxy
  {{- with .Values.kubeEdgeProxy.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["nodes","configmaps","secrets","services"]
  verbs: ["get", "list", "watch"]
