apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}-apiserver
  labels:
    app: network-extension-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app: network-extension-apiserver
  template:
    metadata:
      labels:
        app: network-extension-apiserver
    spec:
      {{- include "apiserver.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: network-extension-apiserver
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - command:
            - apiserver
            - --logtostderr=true
          name: {{ include "backend.fullname" . }}-apiserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "apiserver.image" . }}
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

