apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-extension-apiserver-role
  labels:
    app: network-extension-apiserver
rules:
- apiGroups:
  - crd.projectcalico.org
  resources:
  - ippools
  - ipamblocks
  - ipamhandles
  - blockaffinities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - "apps"
  resources:
  - replicasets
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - get
  - watch
  - list
  - update
  - patch

  
